DROP TABLE IF EXISTS REVIEW_LIKES;
DROP TABLE IF EXISTS REVIEW;
DROP TABLE IF EXISTS film_genre;
DROP TABLE IF EXISTS film_likes;
DROP TABLE IF EXISTS film_director;
DROP TABLE IF EXISTS film;
DROP TABLE IF EXISTS genre;
DROP TABLE IF EXISTS mpa;
DROP TABLE IF EXISTS director;
DROP TABLE IF EXISTS relationship;
DROP TABLE IF EXISTS user_filmorate;
DROP TABLE IF EXISTS feed_event;

CREATE TABLE IF NOT EXISTS genre(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre varchar
);

CREATE TABLE IF NOT EXISTS mpa(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_rate varchar
);

CREATE TABLE IF NOT EXISTS director(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_director VARCHAR
);

CREATE TABLE IF NOT EXISTS film(
    film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar,
    description varchar,
    release_data timestamp,
    duration integer,
    mpa integer REFERENCES mpa(id),
    rate integer
);

CREATE TABLE IF NOT EXISTS film_genre(
    id_film INTEGER REFERENCES film (film_id) ON delete CASCADE,
    genre_id INTEGER REFERENCES genre(id) ON delete CASCADE
);

CREATE TABLE IF NOT EXISTS film_director(
    film_id INTEGER REFERENCES film(film_id) ON delete CASCADE,
    director_id INTEGER REFERENCES director (id) ON delete CASCADE
);

CREATE TABLE IF NOT EXISTS user_filmorate(
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar,
    login varchar,
    name varchar,
    birthday timestamp(8)
);

CREATE TABLE IF NOT EXISTS film_likes(
    id_film INTEGER REFERENCES film(film_id) ON delete CASCADE,
    id_user INTEGER REFERENCES user_filmorate(user_id) ON delete CASCADE
);

CREATE TABLE IF NOT EXISTS relationship(
    id INTEGER REFERENCES user_filmorate(user_id) ON delete CASCADE,
    id_friend INTEGER REFERENCES user_filmorate(user_id) ON delete CASCADE
);
CREATE TABLE IF NOT EXISTS REVIEW (
	REVIEW_ID INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	CONTENT CHARACTER VARYING(100),
	IS_POSITIVE BIT,
	USER_ID INTEGER REFERENCES user_filmorate(user_id) ON delete CASCADE,
	FILM_ID INTEGER REFERENCES user_filmorate(user_id) ON delete CASCADE,
	USEFUL INTEGER
);

CREATE TABLE IF NOT EXISTS REVIEW_LIKES (
	REVIEW_ID INTEGER REFERENCES REVIEW(REVIEW_ID) ON delete CASCADE,
	USER_ID INTEGER REFERENCES user_filmorate(user_id) ON delete CASCADE,
	IS_POSITIVE BIT
);

CREATE TABLE IF NOT EXISTS feed_event (
                                          event_time number not null, event_type varchar, event_operation varchar,
                                          user_id INTEGER NOT NULL,
                                          event_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          entity_id INTEGER NOT NULL
);